<?php

declare(strict_types=1);

namespace Avax\Framework\System\Capabilities\Routing;

use Avax\Framework\System\Capabilities\Routing\Foundation\RouteCacheFailed;

/**
 * CacheRouteTable — Compiles and writes the route cache.
 *
 * Route caching stores a compiled route table for faster loading in production.
 * This is the foundation for V4 route cache optimization.
 */
final readonly class CacheRouteTable
{
    public function __construct(
        private string $cacheDirectory = '',
    ) {
    }

    /**
     * @param  array<string, mixed>  $routeTable
     */
    public function write(array $routeTable): string
    {
        $dir = $this->resolveCacheDirectory();

        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $cacheFile = $dir.'/routes.php';
        $metaFile = $dir.'/routes.php.meta';

        $phpCode = $this->generateCacheFile($routeTable);
        file_put_contents($cacheFile, $phpCode, LOCK_EX);

        $meta = json_encode([
            'timestamp' => time(),
            'route_count' => count($routeTable),
            'php_version' => PHP_VERSION,
        ], JSON_THROW_ON_ERROR);

        file_put_contents($metaFile, $meta, LOCK_EX);

        return $cacheFile;
    }

    /**
     * @param  array<string, mixed>  $routeTable
     */
    private function generateCacheFile(array $routeTable): string
    {
        $export = var_export($routeTable, true);

        return <<<PHP
<?php

declare(strict_types=1);

// Route cache — generated by AvaX route:cache
// Do not edit manually. Run `php avax route:cache` to regenerate.

return {$export};
PHP;
    }

    private function resolveCacheDirectory(): string
    {
        if ($this->cacheDirectory !== '') {
            return $this->cacheDirectory;
        }

        $projectRoot = dirname(__DIR__, 4);

        return $projectRoot.'/storage/framework/cache/routes';
    }
}
