<?php

declare(strict_types=1);

namespace Avax\Cache\System\Capabilities\CompiledCache\ManageCompiledCache;

use Closure;

final class BuildCompiledPhpPayload
{
    public function build(mixed $payload) : string
    {
        $this->validate(payload: $payload);

        $exported = $this->export(payload: $payload);

        return <<<PHP
            <?php
            
            declare(strict_types=1);
            
            /**
             * This file is generated by Avax Compiled Cache.
             * Do not edit manually.
             */
            
            return {$exported};
            PHP;
    }

    private function validate(mixed $payload) : void
    {
        if ($payload instanceof Closure) {
            throw new CompiledCachePayloadWasInvalid(
                reason: 'Closures cannot be serialized to compiled PHP files'
            );
        }

        if (! is_array($payload) && ! is_scalar($payload) && $payload !== null) {
            throw new CompiledCachePayloadWasInvalid(reason: sprintf(
                                                                 'Type %s cannot be exported to PHP',
                                                                 gettype($payload)
                                                             ));
        }

        if (is_array($payload)) {
            $this->validateArray(data: $payload);
        }
    }

    private function validateArray(array $data) : void
    {
        foreach ($data as $key => $value) {
            if (is_string($key) && $key === '') {
                throw new CompiledCachePayloadWasInvalid(
                    reason: 'Empty array keys are not allowed'
                );
            }

            if (is_array($value)) {
                $this->validateArray(data: $value);
            }

            if ($value instanceof Closure) {
                throw new CompiledCachePayloadWasInvalid(
                    reason: 'Closures in arrays cannot be serialized'
                );
            }

            if (is_resource($value)) {
                throw new CompiledCachePayloadWasInvalid(
                    reason: 'Resources cannot be serialized'
                );
            }
        }
    }

    private function export(mixed $payload) : string
    {
        if (is_array($payload)) {
            return var_export($payload, true);
        }

        if (is_scalar($payload) || $payload === null) {
            return var_export($payload, true);
        }

        throw new CompiledCachePayloadWasInvalid(
            reason: 'Unsupported payload type'
        );
    }
}