<?php

declare(strict_types=1);

namespace Avax\Tooling\PreCommit;

final class AvaxPreCommitHook
{
    private const string MARKER = 'AVAX_PRE_COMMIT_HOOK=1';

    public static function marker(): string
    {
        return self::MARKER;
    }

    public static function isGeneratedByAvax(string $content): bool
    {
        return str_contains($content, self::MARKER);
    }

    public static function render(string $phpBinary): string
    {
        $template = <<<'HOOK_WRAP'
            #!/usr/bin/env sh
            # Avax Pre-Commit Hook
            # Generated by tooling/pre-commit/install-hook.php
            # Do not edit this file manually. Re-run the installer instead.
            # {{AVAX_MARKER}}
            
            set -eu
            
            HOOK_DIR = "$(CDPATH= cd -- "$(dirname-- "$0")" && pwd)"
            PROJECT_ROOT = "$(git -C "$HOOK_DIR /../.." rev-parse --show-toplevel 2>/dev/null || true)"
            
            if [-z "$PROJECT_ROOT" ] then
                PROJECT_ROOT = "$(cd "$HOOK_DIR /../.." && pwd)"
            fi
            
            PRE_COMMIT_SCRIPT = "$PROJECT_ROOT/tooling/pre-commit/run-pre-commit.php"
            
            if [! -f "$PRE_COMMIT_SCRIPT" ] then
                echo "Avax pre-commit error: script not found: $PRE_COMMIT_SCRIPT" >&2
                exit 1
            fi
            
            exec {
                    {
                        PHP_BINARY}
                } "$PRE_COMMIT_SCRIPT" "$@"
            HOOK_WRAP;

        return str_replace(
            search: ['{{AVAX_MARKER}}', '{{PHP_BINARY}}'],
            replace: [self::MARKER, Shell::quote($phpBinary)],
            subject: $template,
        );
    }
}
