#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Git Hook Installer
 *
 * Installs the pre-commit hook for Avax project.
 *
 * Usage:
 *   php tooling/pre-commit/install-hook.php           # Interactive install
 *   php tooling/pre-commit/install-hook.php --force   # Overwrite existing
 *   php tooling/pre-commit/install-hook.php --uninstall # Remove hook
 */

$rootDir = dirname(__DIR__, 2);
$hooksDir = $rootDir . '/.git/hooks';
$sourceFile = $rootDir . '/tooling/pre-commit/run-pre-commit.php';
$targetFile = $hooksDir . '/pre-commit';

function main(): int
{
    global $rootDir, $hooksDir, $sourceFile, $targetFile;

    $args = $argv ?? [];

    if (in_array('--uninstall', $args, true)) {
        return uninstallHook($targetFile);
    }

    $force = in_array('--force', $args, true);

    if (! is_dir($hooksDir)) {
        echo "❌ Error: .git/hooks directory not found. Is this a git repository?\n";
        return 1;
    }

    if (! file_exists($sourceFile)) {
        echo "❌ Error: Source hook file not found: {$sourceFile}\n";
        return 1;
    }

    // Check if hook already exists
    if (file_exists($targetFile) && ! $force) {
        echo "⚠️  Pre-commit hook already exists.\n";
        echo "   Use --force to overwrite.\n";
        echo "   Use --uninstall to remove.\n";
        return 1;
    }

    // Create the hook content
    $hookContent = generateHookContent($sourceFile);

    // Write the hook
    if (file_put_contents($targetFile, $hookContent) === false) {
        echo "❌ Error: Failed to write hook file.\n";
        return 1;
    }

    // Make executable
    chmod($targetFile, 0755);

    echo "✅ Pre-commit hook installed successfully!\n";
    echo "   Location: {$targetFile}\n";
    echo "\n";
    echo "The hook will run discipline checks before each commit.\n";
    echo "To bypass the hook temporarily, use: git commit --no-verify\n";

    return 0;
}

function generateHookContent(string $sourceFile): string
{
    $absoluteSource = realpath($sourceFile) ?: $sourceFile;

    return <<<HOOK
#!/bin/bash
# Avax Pre-Commit Hook
# Generated by tooling/pre-commit/install-hook.php

# Find project root (go up from .git/hooks)
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$HOOK_DIR/../.." && pwd)"

# Run the pre-commit script
exec php "$PROJECT_ROOT/tooling/pre-commit/run-pre-commit.php" "$@"
HOOK;
}

function uninstallHook(string $targetFile): int
{
    if (! file_exists($targetFile)) {
        echo "ℹ️  No pre-commit hook found to remove.\n";
        return 0;
    }

    if (! unlink($targetFile)) {
        echo "❌ Error: Failed to remove hook file.\n";
        return 1;
    }

    echo "✅ Pre-commit hook removed successfully!\n";
    return 0;
}

exit(main());
