<?php

declare(strict_types=1);

namespace Avax\Cache\System\Flows\ClearCompiledCache;

use Avax\Cache\System\Capabilities\ManageCompiledCache\CompiledCacheDirectory;
use Avax\Cache\System\Capabilities\ManageCompiledCache\CompiledCacheManifest;
use Avax\Cache\System\Capabilities\ManageCompiledCache\CompiledCacheName;
use Avax\Cache\System\Capabilities\ManageCompiledCache\DeleteCompiledCacheFile;
use Avax\Cache\System\Capabilities\ManageCompiledCache\ResolveCompiledCachePath;
use Avax\Cache\System\Capabilities\ManageCompiledCache\WriteCompiledCacheManifest;
use Avax\Cache\System\Foundation\Time\Clock;
use Avax\Cache\System\Foundation\Time\SystemClock;

final class ClearCompiledCache
{
    private const GENERATED_HEADER = 'This file is generated by Avax Compiled Cache';

    public function __construct(
        private CompiledCacheDirectory $directory,
        private CompiledCacheManifest $manifest,
        private Clock                 $clock = new SystemClock()
    ) {}

    public function clear(string $name) : void
    {
        $nameObj = new CompiledCacheName($name);

        $deleter = new DeleteCompiledCacheFile($this->directory);
        $deleter->delete($nameObj);

        $this->manifest->remove($nameObj->toString());

        $pathResolver = new ResolveCompiledCachePath($this->directory);
        $manifestPath = $pathResolver->resolveManifestPath();

        $manifestWriter = new WriteCompiledCacheManifest($this->clock);
        $manifestWriter->write($this->manifest, $manifestPath);
    }

    public function clearAll() : void
    {
        foreach ($this->manifest->all() as $entry) {
            $deleter = new DeleteCompiledCacheFile($this->directory);
            $deleter->delete($entry->name);
        }

        $this->manifest = CompiledCacheManifest::empty();

        $pathResolver = new ResolveCompiledCachePath($this->directory);
        $manifestPath = $pathResolver->resolveManifestPath();

        if (file_exists($manifestPath->toString())) {
            unlink($manifestPath->toString());
        }

        $this->deleteOrphanedArtifacts();
    }

    private function deleteOrphanedArtifacts() : void
    {
        $dir = $this->directory->toString();

        if (! is_dir($dir)) {
            return;
        }

        $files = glob($dir . '/*.php');

        if ($files === false) {
            return;
        }

        foreach ($files as $file) {
            if (basename($file) === 'manifest.php') {
                continue;
            }

            $content = file_get_contents($file, offset: 0, length: 500);

            if ($content !== false && str_contains($content, self::GENERATED_HEADER)) {
                unlink($file);
            }
        }
    }
}