<?php

declare(strict_types=1);

$classAliases = [
    'Avax\\DataHandling\\DataTransfer\\DataTransfer'                                        => 'Avax\\DataFoundation\\DataTransfer\\DataTransfer',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\CastWith'                  => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\CastWith',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\Hidden'                    => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\Hidden',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\ListOf'                    => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\ListOf',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\MapFrom'                   => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\MapFrom',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\ValueConversion\\ValueCasterInterface' => 'Avax\\Components\\DataStack\\Data\\System\\Capabilities\\DataTransfer\\Capabilities\\ValueConversion\\ValueCasterInterface',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\ValueConversion\\ValueConversionContext' => 'Avax\\Components\\DataStack\\Data\\System\\Capabilities\\DataTransfer\\Capabilities\\ValueConversion\\ValueConversionContext',
    'Avax\\DataHandling\\DataTransfer\\InspectDataShape\\DataField'                         => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\DataField',
    'Avax\\DataHandling\\ObjectHandling\\DTO\\AbstractDTO'                                  => 'Avax\\Components\\DataStack\\Data\\System\\Capabilities\\DataTransfer\\Foundation\\AbstractDTO',
    'Avax\\DataFoundation\\ObjectHandling\\DTO\\AbstractDTO'                                => 'Avax\\Components\\DataStack\\Data\\System\\Capabilities\\DataTransfer\\Foundation\\AbstractDTO',
    'Avax\\DataFoundation\\Collection'                                                      => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Collection',
    'Avax\\DataFoundation\\Arrhae'                                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Arrhae',
    'Avax\\DataFoundation\\Collections\\Map\\Map'                                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Map\\Map',
    'Avax\\DataFoundation\\Collections\\Set\\Set'                                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Set\\Set',
    'Avax\\DataFoundation\\Collections\\DataList\\DataList'                                 => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\DataList\\DataList',
    'Avax\\DataFoundation\\Collections\\Aggregate\\AverageValues'                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Aggregate\\AverageValues',
    'Avax\\DataFoundation\\Collections\\Aggregate\\SumValues'                               => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Aggregate\\SumValues',
    'Avax\\DataFoundation\\Collections\\Transform\\MapValues'                               => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Transform\\MapValues',
    'Avax\\DataFoundation\\Collections\\Transform\\FilterValues'                            => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Transform\\FilterValues',
    'Avax\\DataFoundation\\Collections\\Search\\MatchTextFuzzily'                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\MatchTextFuzzily',
    'Avax\\DataFoundation\\Collections\\Search\\MatchTextPartially'                         => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\MatchTextPartially',
    'Avax\\DataFoundation\\Collections\\Search\\ContainsValue'                              => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\ContainsValue',
    'Avax\\DataFoundation\\Collections\\Search\\SearchValue'                                => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\SearchValue',
    'Avax\\DataFoundation\\Values\\Option\\Option'                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Option\\Option',
    'Avax\\DataFoundation\\Values\\Option\\Some'                                            => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Option\\Some',
    'Avax\\DataFoundation\\Values\\Option\\None'                                            => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Option\\None',
    'Avax\\DataFoundation\\Values\\Result\\Result'                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Result\\Result',
    'Avax\\DataFoundation\\Values\\Result\\Ok'                                              => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Result\\Success',
    'Avax\\DataFoundation\\Values\\Result\\Error'                                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Result\\Failure',
    'Avax\\DataFoundation\\Composites\\MapEntry\\MapEntry'                                  => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\MapEntry',
    'Avax\\DataFoundation\\Composites\\Pair\\Pair'                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Pair',
    'Avax\\DataFoundation\\Composites\\Tuple\\Tuple2'                                       => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Tuple2',
    'Avax\\DataFoundation\\Composites\\Tuple\\Tuple3'                                       => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Tuple3',
    'Avax\\DataFoundation\\Composites\\Tuple\\Tuple4'                                       => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Tuple4',
    'Avax\\DataFoundation\\Composites\\Record\\Record'                                      => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Record',
    'Avax\\DataFoundation\\Composites\\Record\\RecordField'                                 => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\RecordField',

    // DataShape ecosystem
    'Avax\\DataFoundation\\DataTransfer\\InspectDataShape\\InspectDataShape' => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\InspectDataShape',
    'Avax\\DataFoundation\\DataTransfer\\InspectDataShape\\DataField'                       => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\DataField',
    'Avax\\DataFoundation\\DataTransfer\\InspectDataShape\\DataFieldType'                   => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\DataFieldType',

    // ObjectReading ecosystem
    'Avax\\DataFoundation\\DataTransfer\\ObjectReading\\ReadDataObject'                     => 'Avax\\Components\\Data\\System\\Capabilities\\ObjectReading\\ReadDataObject',
    'Avax\\DataFoundation\\DataTransfer\\ObjectReading\\NormalizeDataObjectValue' => 'Avax\\Components\\Data\\System\\Capabilities\\ObjectReading\\NormalizeDataObjectValue',

    // Serialization flow ecosystem
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\SerializeDataObject'          => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\SerializeDataObject',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToArray'     => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToArray',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToJson'      => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToJson',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToStdClass' => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToStdClass',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToJsonApi'   => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToJsonApi',

    'Avax\\Text\\Text'                                                => 'Avax\\Components\\Text\\System\\PublicSurface\\Text',
    'Avax\\DataHandling\\ObjectHandling\\DTO\\DTOValidationException' => 'Avax\\DataFoundation\\ObjectHandling\\DTO\\DTOValidationException',
    'Avax\\DataHandling\\Validation\\Attributes\\Rules\\EmailRule'    => 'Avax\\DataFoundation\\Validation\\Attributes\\Rules\\EmailRule',
    'Avax\\DataHandling\\Validation\\Attributes\\Rules\\MinLengthRule' => 'Avax\\DataFoundation\\Validation\\Attributes\\Rules\\MinLengthRule',

    // Router compat aliases - only core interfaces exist at new location
    // Other Router aliases removed: old component structure was replaced by HTTP/Router suite
    'Avax\\HTTP\\Router\\Router'                                      => 'Avax\\Components\\HTTP\\Router\\System\\PublicSurface\\Router',
    'Avax\\HTTP\\Router\\RouterInterface'                             => 'Avax\\Components\\HTTP\\Router\\System\\PublicSurface\\RouterInterface',
    'Avax\\HTTP\\Router\\RouterRuntimeInterface' => 'Avax\\Components\\HTTP\\Router\\System\\PublicSurface\\RouterRuntimeInterface',

    'Avax\\Database\\Database'                                                                  => 'Avax\\Components\\DataStack\\Database\\Database',
    'Avax\\Database\\EntityManager'                                                             => 'Avax\\Components\\DataStack\\Database\\EntityManager',
    'Avax\\Database\\Migrations'                                                                => 'Avax\\Components\\DataStack\\Database\\Migrations',
    'Avax\\Database\\Query'                                                                     => 'Avax\\Components\\DataStack\\Database\\Query',
    'Avax\\Database\\Schema'                                                                    => 'Avax\\Components\\DataStack\\Database\\Schema',
    'Avax\\Database\\Telemetry'                                                                 => 'Avax\\Components\\DataStack\\Database\\Telemetry',
    'Avax\\Database\\Transactions'                                                              => 'Avax\\Components\\DataStack\\Database\\Transactions',
    'Avax\\Database\\System\\Capabilities\\Connections\\Connections'                            => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Connections\\Connections',
    'Avax\\Database\\System\\Capabilities\\Connections\\Pools\\ConnectionPool'                  => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Connections\\Pools\\ConnectionPool',
    'Avax\\Database\\System\\Capabilities\\Migrations\\Design\\Column\\DSL\\ColumnDefinition'   => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Migrations\\Design\\Column\\DSL\\ColumnDefinition',
    'Avax\\Database\\System\\Capabilities\\Migrations\\Design\\Column\\Render\\ColumnSQLRenderer' => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Migrations\\Design\\Column\\Render\\ColumnSQLRenderer',
    'Avax\\Database\\System\\Capabilities\\Migrations\\Design\\Table\\Blueprint'                => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Migrations\\Design\\Table\\Blueprint',
    'Avax\\Database\\System\\Capabilities\\ORM\\Attributes\\Column'                             => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Attributes\\Column',
    'Avax\\Database\\System\\Capabilities\\ORM\\Attributes\\Entity'                             => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Attributes\\Entity',
    'Avax\\Database\\System\\Capabilities\\ORM\\Attributes\\GeneratedValue'                     => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Attributes\\GeneratedValue',
    'Avax\\Database\\System\\Capabilities\\ORM\\Attributes\\Id'                                 => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Attributes\\Id',
    'Avax\\Database\\System\\Capabilities\\ORM\\Attributes\\Table'                              => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Attributes\\Table',
    'Avax\\Database\\System\\Capabilities\\ORM\\Repositories\\EntityRepository'                 => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Repositories\\EntityRepository',
    'Avax\\Database\\System\\Capabilities\\Query\\Builder\\QueryBuilder'                        => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Query\\Builder\\QueryBuilder',
    'Avax\\Database\\System\\Capabilities\\Query\\Exceptions\\QueryException'                   => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Query\\Exceptions\\QueryException',
    'Avax\\Database\\System\\Capabilities\\Query\\Grammar\\MySQLGrammar'                        => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Query\\Grammar\\MySQLGrammar',
    'Avax\\Database\\System\\Capabilities\\Transactions\\Exceptions\\TransactionException'      => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\Transactions\\Exceptions\\TransactionException',
    'Avax\\Tests\\Foundation\\Database\\Unit\\Attributes\\Column'                               => 'Avax\\Components\\DataStack\\Database\\System\\Capabilities\\ORM\\Attributes\\Column',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\ServerRequest'                        => 'Avax\\Components\\Request\\System\\PublicSurface\\ServerRequest',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestInit'                          => 'Avax\\Components\\Request\\System\\Capabilities\\RequestInit',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\ServerInit'                           => 'Avax\\Components\\Request\\System\\Capabilities\\ServerInit',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestHeaders\\RequestHeaders'       => 'Avax\\Components\\Request\\System\\Capabilities\\RequestHeaders\\RequestHeaders',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestBody\\RequestBody'             => 'Avax\\Components\\Request\\System\\Capabilities\\RequestBody\\RequestBody',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestBody\\ParsedBody'              => 'Avax\\Components\\Request\\System\\Capabilities\\RequestBody\\ParsedBody',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestCookies\\RequestCookies'       => 'Avax\\Components\\Request\\System\\Capabilities\\RequestCookies\\RequestCookies',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\UploadedFiles\\UploadedFiles'         => 'Avax\\Components\\Request\\System\\Capabilities\\UploadedFiles\\UploadedFiles',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestAttributes\\RequestAttributes' => 'Avax\\Components\\Request\\System\\Capabilities\\RequestAttributes\\RequestAttributes',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestTarget\\ReadRequestTarget'     => 'Avax\\Components\\Request\\System\\Capabilities\\RequestTarget\\ReadRequestTarget',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestedInputs\\RequestedInputs'     => 'Avax\\Components\\Request\\System\\Capabilities\\RequestedInputs\\RequestedInputs',
    'Avax\\HTTP\\Request\\Request'                                                              => 'Avax\\Components\\HTTP\\Request\\Request',
    'Avax\\HTTP\\Request\\RequestDtoFactory'                                                    => 'Avax\\HTTP\\Request\\RequestDtoFactory',
    'Avax\\Logging\\LoggerFactory'                                                              => 'Avax\\Components\\Logging\\System\\Configuration\\RegisterLogging',
    'Avax\\Cache\\Cache'                                                                        => 'Avax\\Components\\Cache\\System\\PublicSurface\\Cache',
    'Avax\\Config\\Architecture\\DDD\\AppPath'                                                  => 'Avax\\Components\\Config\\System\\Capabilities\\Architecture\\AppPath',
    'Avax\\DumpDebugger\\DumpDebugger'                                                          => 'Avax\\Components\\DumpDebugger\\System\\PublicSurface\\Dump',
    'Avax\\HTTP\\HttpKernel'                                                                    => 'Avax\\Components\\HTTP\\System\\Capabilities\\Kernel\\HttpKernel',
    'Avax\\HTTP\\AppKernel'                                                                     => 'Avax\\Components\\HTTP\\System\\Capabilities\\Kernel\\AppKernel',
    'Avax\\HTTP\\ResolveRouteFromHttpRequest'                                                   => 'Avax\\Components\\HTTP\\System\\Flows\\Routing\\ResolveRouteFromHttpRequest',
    'Avax\\HTTP\\Response\\Response'                                                            => 'Avax\\Components\\Response\\System\\PublicSurface\\Response',
    'Avax\\HTTP\\Response\\ResponseEmitter'                                                     => 'Avax\\Components\\Response\\System\\Capabilities\\ResponseEmitter',
    'Avax\\HTTP\\Response\\Capabilities\\Message\\ResponseMessage'                              => 'Avax\\Components\\Response\\System\\Capabilities\\Message\\ResponseMessage',
    'Avax\\HTTP\\Response\\Capabilities\\Headers\\ResponseHeaders'                              => 'Avax\\Components\\Response\\System\\Capabilities\\Headers\\ResponseHeaders',
    'Avax\\HTTP\\Response\\Capabilities\\Body\\ResponseBody'                                    => 'Avax\\Components\\Response\\System\\Capabilities\\Body\\ResponseBody',
    'Avax\\HTTP\\Response\\Capabilities\\Caching\\CacheControl'                                 => 'Avax\\Components\\Response\\System\\Capabilities\\Caching\\CacheControl',
    'Avax\\HTTP\\Response\\Capabilities\\Caching\\Etag'                                         => 'Avax\\Components\\Response\\System\\Capabilities\\Caching\\Etag',
    'Avax\\HTTP\\Response\\Capabilities\\Caching\\LastModified'                                 => 'Avax\\Components\\Response\\System\\Capabilities\\Caching\\LastModified',
    'Avax\\HTTP\\Response\\Flows\\BuildResponse\\BuildResponse'                                 => 'Avax\\Components\\Response\\System\\Flows\\BuildResponse\\BuildResponse',
    'Avax\\HTTP\\Response\\Flows\\EmitResponse\\EmitResponse'                                   => 'Avax\\Components\\Response\\System\\Flows\\EmitResponse\\EmitResponse',
    'Avax\\HTTP\\RouterBootstrapper'                                                            => 'Avax\\Components\\HTTP\\System\\Configuration\\RouterBootstrapper',
    'Avax\\HTTP\\Session\\Session'                                                              => 'Avax\\Components\\HTTP\\Session\\System\\PublicSurface\\Session',
    'Avax\\HTTP\\Context\\HttpContext'                                                          => 'Avax\\Components\\HTTP\\Context\\System\\PublicSurface\\HttpContext',
    'Avax\\Presentation\\View\\View'                                                            => 'Avax\\Components\\Presentation\\View\\System\\PublicSurface\\View',
    'Avax\\Application\\Filesystem\\Filesystem'                                                 => 'Avax\\Components\\Application\\Filesystem\\System\\PublicSurface\\Filesystem',
    'Avax\\Application\\Config\\Config'                                                         => 'Avax\\Components\\Application\\Config\\System\\PublicSurface\\Config',
    'Avax\\Components\\Application\\Container\\System\\ContainerInterface'                      => 'Avax\\Components\\Application\\Container\\System\\PublicSurface\\ContainerInterface',
    'Avax\\Components\\Container\\ContainerInterface'                                           => 'Avax\\Components\\Application\\Container\\System\\PublicSurface\\ContainerInterface',
];

foreach ($classAliases as $alias => $target) {
    if (class_exists($alias, false) || interface_exists($alias, false)) {
        continue;
    }

    if (interface_exists($target) || class_exists($target)) {
        class_alias(
            class     : $target,
            alias     : $alias,
            autoload  : false,
        );
    }
}
