<?php

declare(strict_types=1);

$classAliases = [
    'Avax\\DataHandling\\DataTransfer\\DataTransfer'                                          => 'Avax\\DataFoundation\\DataTransfer\\DataTransfer',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\CastWith'                    => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\CastWith',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\Hidden'                      => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\Hidden',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\ListOf'                      => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\ListOf',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\Attributes\\MapFrom'                     => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\Attributes\\MapFrom',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\ValueConversion\\ValueCasterInterface'   => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\ValueConversion\\ValueCasterInterface',
    'Avax\\DataHandling\\DataTransfer\\Capabilities\\ValueConversion\\ValueConversionContext' => 'Avax\\DataFoundation\\DataTransfer\\Capabilities\\ValueConversion\\ValueConversionContext',
    'Avax\\DataHandling\\DataTransfer\\InspectDataShape\\DataField'                        => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\DataField',
    'Avax\\DataHandling\\ObjectHandling\\DTO\\AbstractDTO'                                    => 'Avax\\Components\\Persistence\\System\\Capabilities\\ObjectHandling\\DTO\\AbstractDTO',
    'Avax\\DataFoundation\\ObjectHandling\\DTO\\AbstractDTO'                                  => 'Avax\\Components\\Persistence\\System\\Capabilities\\ObjectHandling\\DTO\\AbstractDTO',
    'Avax\\DataFoundation\\Collection'                                                        => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Collection',
    'Avax\\DataFoundation\\Arrhae'                                                         => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Arrhae',
    'Avax\\DataFoundation\\Collections\\Map\\Map'                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Map\\Map',
    'Avax\\DataFoundation\\Collections\\Set\\Set'                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Set\\Set',
    'Avax\\DataFoundation\\Collections\\DataList\\DataList'                                => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\DataList\\DataList',
    'Avax\\DataFoundation\\Collections\\Aggregate\\AverageValues'                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Aggregate\\AverageValues',
    'Avax\\DataFoundation\\Collections\\Aggregate\\SumValues'                              => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Aggregate\\SumValues',
    'Avax\\DataFoundation\\Collections\\Transform\\MapValues'                              => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Transform\\MapValues',
    'Avax\\DataFoundation\\Collections\\Transform\\FilterValues'                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Transform\\FilterValues',
    'Avax\\DataFoundation\\Collections\\Search\\MatchTextFuzzily'                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\MatchTextFuzzily',
    'Avax\\DataFoundation\\Collections\\Search\\MatchTextPartially'                        => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\MatchTextPartially',
    'Avax\\DataFoundation\\Collections\\Search\\ContainsValue'                             => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\ContainsValue',
    'Avax\\DataFoundation\\Collections\\Search\\SearchValue'                               => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Operators\\Search\\SearchValue',
    'Avax\\DataFoundation\\Values\\Option\\Option'                                         => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Option\\Option',
    'Avax\\DataFoundation\\Values\\Option\\Some'                                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Option\\Some',
    'Avax\\DataFoundation\\Values\\Option\\None'                                           => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Option\\None',
    'Avax\\DataFoundation\\Values\\Result\\Result'                                         => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Result\\Result',
    'Avax\\DataFoundation\\Values\\Result\\Ok'                                             => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Result\\Success',
    'Avax\\DataFoundation\\Values\\Result\\Error'                                          => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Values\\Result\\Failure',
    'Avax\\DataFoundation\\Composites\\MapEntry\\MapEntry'                                 => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\MapEntry',
    'Avax\\DataFoundation\\Composites\\Pair\\Pair'                                         => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Pair',
    'Avax\\DataFoundation\\Composites\\Tuple\\Tuple2'                                      => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Tuple2',
    'Avax\\DataFoundation\\Composites\\Tuple\\Tuple3'                                      => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Tuple3',
    'Avax\\DataFoundation\\Composites\\Tuple\\Tuple4'                                      => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Tuple4',
    'Avax\\DataFoundation\\Composites\\Record\\Record'                                     => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\Record',
    'Avax\\DataFoundation\\Composites\\Record\\RecordField'                                => 'Avax\\Components\\Data\\System\\Capabilities\\Collections\\Internal\\Composites\\RecordField',

    // DataShape ecosystem
    'Avax\\DataFoundation\\DataTransfer\\InspectDataShape\\InspectDataShape'               => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\InspectDataShape',
    'Avax\\DataFoundation\\DataTransfer\\InspectDataShape\\DataField'                      => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\DataField',
    'Avax\\DataFoundation\\DataTransfer\\InspectDataShape\\DataFieldType'                  => 'Avax\\Components\\Data\\System\\Capabilities\\DataShape\\DataFieldType',

    // ObjectReading ecosystem
    'Avax\\DataFoundation\\DataTransfer\\ObjectReading\\ReadDataObject'                    => 'Avax\\Components\\Data\\System\\Capabilities\\ObjectReading\\ReadDataObject',
    'Avax\\DataFoundation\\DataTransfer\\ObjectReading\\NormalizeDataObjectValue'          => 'Avax\\Components\\Data\\System\\Capabilities\\ObjectReading\\NormalizeDataObjectValue',

    // Serialization flow ecosystem
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\SerializeDataObject'         => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\SerializeDataObject',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToArray'    => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToArray',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToJson'     => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToJson',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToStdClass' => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToStdClass',
    'Avax\\DataFoundation\\DataTransfer\\SerializeDataObject\\ConvertDataObjectToJsonApi'  => 'Avax\\Components\\Data\\System\\Flows\\SerializeDataObject\\ConvertDataObjectToJsonApi',

    'Avax\\Text\\Text'                                                                        => 'Avax\\Components\\Text\\System\\PublicSurface\\Text',
    'Avax\\DataHandling\\ObjectHandling\\DTO\\DTOValidationException'                         => 'Avax\\DataFoundation\\ObjectHandling\\DTO\\DTOValidationException',
    'Avax\\DataHandling\\Validation\\Attributes\\Rules\\EmailRule'                            => 'Avax\\DataFoundation\\Validation\\Attributes\\Rules\\EmailRule',
    'Avax\\DataHandling\\Validation\\Attributes\\Rules\\MinLengthRule'                        => 'Avax\\DataFoundation\\Validation\\Attributes\\Rules\\MinLengthRule',

    'Avax\\HTTP\\Router\\Router'                                                                => 'Avax\\Components\\Router\\System\\PublicSurface\\Router',
    'Avax\\HTTP\\Router\\RouterInterface'                                                       => 'Avax\\Components\\Router\\System\\PublicSurface\\RouterInterface',
    'Avax\\HTTP\\Router\\RouterRuntimeInterface'                                                => 'Avax\\Components\\Router\\System\\PublicSurface\\RouterRuntimeInterface',
    'Avax\\HTTP\\Router\\HttpMethod'                                                            => 'Avax\\Components\\Router\\System\\PublicSurface\\HttpMethod',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\HttpRequestRouter'                      => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\HttpRequestRouter',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\RouterKernel'                                 => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\RouterKernel',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\RouterDsl'                              => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\RouterDsl',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Definitions\\RouteBuilder'              => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Definitions\\RouteBuilder',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Definitions\\RouteRegistry'             => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Definitions\\RouteRegistry',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Definitions\\RouterRegistrar'           => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Definitions\\RouterRegistrar',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Files\\RouteCollector'                  => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Files\\RouteCollector',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Files\\RouteFileRegistrar'              => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Files\\RouteFileRegistrar',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Files\\RouteRegistrarProxy'             => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Files\\RouteRegistrarProxy',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Groups\\RouteGroupFrames'               => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Groups\\RouteGroupFrames',
    'Avax\\HTTP\\Router\\System\\Flows\\RegisterRoutes\\Groups\\RouteGroupContext'              => 'Avax\\Components\\Router\\System\\Flows\\RegisterRoutes\\Groups\\RouteGroupContext',
    'Avax\\HTTP\\Router\\System\\Capabilities\\RouteDefinition\\RouteDefinition'                => 'Avax\\Components\\Router\\System\\Capabilities\\RouteDefinition\\RouteDefinition',
    'Avax\\HTTP\\Router\\System\\Capabilities\\RouteDefinition\\RouteKey'                       => 'Avax\\Components\\Router\\System\\Capabilities\\RouteDefinition\\RouteKey',
    'Avax\\HTTP\\Router\\System\\Capabilities\\RouteDefinition\\DuplicatePolicy'                => 'Avax\\Components\\Router\\System\\Capabilities\\RouteDefinition\\DuplicatePolicy',
    'Avax\\HTTP\\Router\\System\\Capabilities\\RouterMetrics\\RouterMetricsCollector'           => 'Avax\\Components\\Router\\System\\Capabilities\\RouterMetrics\\RouterMetricsCollector',
    'Avax\\HTTP\\Router\\System\\Capabilities\\RouterTrace\\RouterTrace'                        => 'Avax\\Components\\Router\\System\\Capabilities\\RouterTrace\\RouterTrace',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\RouteResolutionContext'                 => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\RouteResolutionContext',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\Constraints\\RouteConstraintValidator'  => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\Constraints\\RouteConstraintValidator',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\HeadRequests\\ApplyHeadRequestFallback' => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\HeadRequests\\ApplyHeadRequestFallback',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\Matching\\DomainPatternCompiler'        => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\Matching\\DomainPatternCompiler',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\Matching\\RouteMatcherInterface'        => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\Matching\\RouteMatcherInterface',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\Request\\RouteRequestInjector'          => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\Request\\RouteRequestInjector',
    'Avax\\HTTP\\Router\\System\\Flows\\ResolveRequest\\Paths\\PathNormalizer'                  => 'Avax\\Components\\Router\\System\\Flows\\ResolveRequest\\Paths\\PathNormalizer',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Dispatch\\RouteExecutor'                      => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Dispatch\\RouteExecutor',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Pipeline\\RoutePipeline'                      => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Pipeline\\RoutePipeline',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Pipeline\\RoutePipelineFactory'               => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Pipeline\\RoutePipelineFactory',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Pipeline\\StageChain'                         => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Pipeline\\StageChain',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Pipeline\\RouteStage'                         => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Pipeline\\RouteStage',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Pipeline\\RouteMiddleware'                    => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Pipeline\\RouteMiddleware',
    'Avax\\HTTP\\Router\\System\\Flows\\RunRoute\\Responses\\ErrorResponseFactory'              => 'Avax\\Components\\Router\\System\\Flows\\RunRoute\\Responses\\ErrorResponseFactory',

    // Router Exceptions
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\RouterException'                       => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\RouterException',
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\RouterExceptionInterface'              => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\RouterExceptionInterface',
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\RouteNotFoundException'                => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\RouteNotFoundException',
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\MethodNotAllowedException'             => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\MethodNotAllowedException',
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\DuplicateRouteException'               => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\DuplicateRouteException',
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\ReservedRouteNameException'            => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\ReservedRouteNameException',
    'Avax\\HTTP\\Router\\System\\Foundation\\Exceptions\\InvalidRouteException'                 => 'Avax\\Components\\Router\\System\\Foundation\\Exceptions\\InvalidRouteException',

    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\ServerRequest'                        => 'Avax\\Components\\Request\\System\\PublicSurface\\ServerRequest',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestInit'                          => 'Avax\\Components\\Request\\System\\Capabilities\\RequestInit',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\ServerInit'                           => 'Avax\\Components\\Request\\System\\Capabilities\\ServerInit',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestHeaders\\RequestHeaders'       => 'Avax\\Components\\Request\\System\\Capabilities\\RequestHeaders\\RequestHeaders',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestBody\\RequestBody'             => 'Avax\\Components\\Request\\System\\Capabilities\\RequestBody\\RequestBody',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestBody\\ParsedBody'              => 'Avax\\Components\\Request\\System\\Capabilities\\RequestBody\\ParsedBody',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestCookies\\RequestCookies'       => 'Avax\\Components\\Request\\System\\Capabilities\\RequestCookies\\RequestCookies',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\UploadedFiles\\UploadedFiles'         => 'Avax\\Components\\Request\\System\\Capabilities\\UploadedFiles\\UploadedFiles',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestAttributes\\RequestAttributes' => 'Avax\\Components\\Request\\System\\Capabilities\\RequestAttributes\\RequestAttributes',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestTarget\\ReadRequestTarget'     => 'Avax\\Components\\Request\\System\\Capabilities\\RequestTarget\\ReadRequestTarget',
    'Avax\\HTTP\\Request\\ServerRequest\\IncomingRequest\\RequestedInputs\\RequestedInputs'     => 'Avax\\Components\\Request\\System\\Capabilities\\RequestedInputs\\RequestedInputs',
    'Avax\\HTTP\\Request\\Request'                                                              => 'Avax\\Components\\HTTP\\Request\\Request',
    'Avax\\HTTP\\Request\\RequestDtoFactory'                                                  => 'Avax\\HTTP\\Request\\RequestDtoFactory',
    'Avax\\Logging\\LoggerFactory'                                                            => 'Avax\\Components\\Logging\\System\\Configuration\\RegisterLogging',
    'Avax\\Cache\\Cache'                                                                      => 'Avax\\Components\\Cache\\System\\PublicSurface\\Cache',
    'Avax\\Config\\Architecture\\DDD\\AppPath'                                                => 'Avax\\Components\\Config\\System\\Capabilities\\Architecture\\AppPath',
    'Avax\\DumpDebugger\\DumpDebugger'                                                        => 'Avax\\Components\\DumpDebugger\\System\\PublicSurface\\Dump',
    'Avax\\HTTP\\HttpKernel'                                                                  => 'Avax\\Components\\HTTP\\System\\Capabilities\\Kernel\\HttpKernel',
    'Avax\\HTTP\\AppKernel'                                                                   => 'Avax\\Components\\HTTP\\System\\Capabilities\\Kernel\\AppKernel',
    'Avax\\HTTP\\ResolveRouteFromHttpRequest'                                                 => 'Avax\\Components\\HTTP\\System\\Flows\\Routing\\ResolveRouteFromHttpRequest',
    'Avax\\HTTP\\Response\\Response'                                                            => 'Avax\\Components\\Response\\System\\PublicSurface\\Response',
    'Avax\\HTTP\\Response\\ResponseEmitter'                                                     => 'Avax\\Components\\Response\\System\\Capabilities\\ResponseEmitter',
    'Avax\\HTTP\\Response\\Capabilities\\Message\\ResponseMessage'                              => 'Avax\\Components\\Response\\System\\Capabilities\\Message\\ResponseMessage',
    'Avax\\HTTP\\Response\\Capabilities\\Headers\\ResponseHeaders'                              => 'Avax\\Components\\Response\\System\\Capabilities\\Headers\\ResponseHeaders',
    'Avax\\HTTP\\Response\\Capabilities\\Body\\ResponseBody'                                    => 'Avax\\Components\\Response\\System\\Capabilities\\Body\\ResponseBody',
    'Avax\\HTTP\\Response\\Capabilities\\Caching\\CacheControl'                                 => 'Avax\\Components\\Response\\System\\Capabilities\\Caching\\CacheControl',
    'Avax\\HTTP\\Response\\Capabilities\\Caching\\Etag'                                         => 'Avax\\Components\\Response\\System\\Capabilities\\Caching\\Etag',
    'Avax\\HTTP\\Response\\Capabilities\\Caching\\LastModified'                                 => 'Avax\\Components\\Response\\System\\Capabilities\\Caching\\LastModified',
    'Avax\\HTTP\\Response\\Flows\\BuildResponse\\BuildResponse'                                 => 'Avax\\Components\\Response\\System\\Flows\\BuildResponse\\BuildResponse',
    'Avax\\HTTP\\Response\\Flows\\EmitResponse\\EmitResponse'                                   => 'Avax\\Components\\Response\\System\\Flows\\EmitResponse\\EmitResponse',
    'Avax\\HTTP\\RouterBootstrapper'                                                          => 'Avax\\Components\\HTTP\\System\\Configuration\\RouterBootstrapper',
];

foreach ($classAliases as $alias => $target) {
    if (class_exists($alias, false) || interface_exists($alias, false)) {
        continue;
    }

    if (interface_exists($target) || class_exists($target)) {
        class_alias(
            class     : $target,
            alias     : $alias,
            autoload  : false
        );
    }
}
