<?php

declare(strict_types=1);

namespace Avax\Cache\System\Capabilities\ManageCompiledCache;

use Closure;

final class BuildCompiledPhpPayload
{
    public function build(mixed $payload) : string
    {
        $this->validate($payload);

        $exported = $this->export($payload);

        return <<<PHP
            <?php
            
            declare(strict_types=1);
            
            /**
             * This file is generated by Avax Compiled Cache.
             * Do not edit manually.
             */
            
            return {$exported};
            PHP;
    }

    private function validate(mixed $payload) : void
    {
        if ($payload instanceof Closure) {
            throw new CompiledCachePayloadWasInvalid(
                'Closures cannot be serialized to compiled PHP files'
            );
        }

        if (! is_array($payload) && ! is_scalar($payload) && $payload !== null) {
            throw new CompiledCachePayloadWasInvalid(sprintf(
                                                         'Type %s cannot be exported to PHP',
                                                         gettype($payload)
                                                     ));
        }

        if (is_array($payload)) {
            $this->validateArray($payload);
        }
    }

    private function validateArray(array $data) : void
    {
        foreach ($data as $key => $value) {
            if (is_string($key) && $key === '') {
                throw new CompiledCachePayloadWasInvalid(
                    'Empty array keys are not allowed'
                );
            }

            if (is_array($value)) {
                $this->validateArray($value);
            }

            if ($value instanceof Closure) {
                throw new CompiledCachePayloadWasInvalid(
                    'Closures in arrays cannot be serialized'
                );
            }

            if (is_resource($value)) {
                throw new CompiledCachePayloadWasInvalid(
                    'Resources cannot be serialized'
                );
            }
        }
    }

    private function export(mixed $payload) : string
    {
        if (is_array($payload)) {
            return var_export($payload, true);
        }

        if (is_scalar($payload) || $payload === null) {
            return var_export($payload, true);
        }

        throw new CompiledCachePayloadWasInvalid(
            'Unsupported payload type'
        );
    }
}