<?php

declare(strict_types=1);

namespace Avax\Cache\Tests\Unit\Cache\Capabilities\ManageCompiledCache;

use Avax\Cache\System\Capabilities\ManageCompiledCache\BuildCompiledPhpPayload;
use Avax\Cache\System\Capabilities\ManageCompiledCache\CompiledCachePayloadWasInvalid;
use PHPUnit\Framework\TestCase;

final class BuildCompiledPhpPayloadTest extends TestCase
{
    private BuildCompiledPhpPayload $builder;

    public function test_it_builds_php_file_that_returns_array_payload() : void
    {
        $payload = ['key' => 'value', 'count' => 42];

        $php = $this->builder->build($payload);

        $this->assertStringStartsWith('<?php', $php);
        $this->assertStringContainsString('declare(strict_types=1)', $php);
        $this->assertStringContainsString('This file is generated by Avax Compiled Cache', $php);
        $this->assertStringContainsString('return ', $php);
    }

    public function test_it_includes_strict_types_declaration() : void
    {
        $php = $this->builder->build(['test' => true]);

        $this->assertStringContainsString("declare(strict_types=1);", $php);
    }

    public function test_it_includes_generated_file_warning() : void
    {
        $php = $this->builder->build(['test' => true]);

        $this->assertStringContainsString('This file is generated by Avax Compiled Cache', $php);
    }

    public function test_it_rejects_closure_payload() : void
    {
        $this->expectException(CompiledCachePayloadWasInvalid::class);
        $this->expectExceptionMessage('Closures cannot be serialized');

        $this->builder->build(fn () => 'value');
    }

    public function test_it_rejects_unexportable_payload() : void
    {
        $resource = fopen('php://memory', 'r');

        $this->expectException(CompiledCachePayloadWasInvalid::class);
        $this->expectExceptionMessage('Resources cannot be serialized');

        $this->builder->build($resource);
    }

    public function test_it_rejects_empty_array_keys() : void
    {
        $this->expectException(CompiledCachePayloadWasInvalid::class);
        $this->expectExceptionMessage('Empty array keys');

        $this->builder->build(['' => 'value']);
    }

    public function test_it_accepts_scalar_payloads() : void
    {
        $php = $this->builder->build('string value');
        $this->assertStringContainsString("'string value'", $php);

        $php = $this->builder->build(123);
        $this->assertStringContainsString('123', $php);

        $php = $this->builder->build(true);
        $this->assertStringContainsString('true', $php);

        $php = $this->builder->build(null);
        $this->assertStringContainsString('null', $php);
    }

    protected function setUp() : void
    {
        $this->builder = new BuildCompiledPhpPayload();
    }
}