<?php

declare(strict_types=1);

namespace Avax\Components\Application\Cache\System\Flows\Compiled\ClearCompiledCache;

use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheDirectory;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheManifest;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheName;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\DeleteCompiledCacheFile;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\ResolveCompiledCachePath;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\WriteCompiledCacheManifest;
use Avax\Components\Application\Filesystem\System\PublicSurface\Filesystem;

final class ClearCompiledCache
{
    private const string GENERATED_HEADER = 'This file is generated by Avax Compiled Cache';

    public function __construct(
        private readonly CompiledCacheDirectory $compiledCacheDirectory,
        private CompiledCacheManifest           $compiledCacheManifest,
        private ?Filesystem                     $filesystem = null,
    )
    {
    }

    public function clear(string $name): void
    {
        $compiledCacheName = new CompiledCacheName(name: $name);

        $deleteCompiledCacheFile = new DeleteCompiledCacheFile($this->compiledCacheDirectory);
        $deleteCompiledCacheFile->delete($compiledCacheName);

        $this->compiledCacheManifest->remove($compiledCacheName->toString());

        $resolveCompiledCachePath = new ResolveCompiledCachePath($this->compiledCacheDirectory);
        $compiledCachePath = $resolveCompiledCachePath->resolveManifestPath();

        $writeCompiledCacheManifest = new WriteCompiledCacheManifest();
        $writeCompiledCacheManifest->write($this->compiledCacheManifest, $compiledCachePath);
    }

    public function clearAll(): void
    {
        $fs = $this->filesystem ?? new Filesystem();

        foreach ($this->compiledCacheManifest->all() as $entry) {
            $deleter = new DeleteCompiledCacheFile($this->compiledCacheDirectory);
            $deleter->delete($entry->name);
        }

        $this->compiledCacheManifest = CompiledCacheManifest::empty();

        $resolveCompiledCachePath = new ResolveCompiledCachePath($this->compiledCacheDirectory);
        $compiledCachePath = $resolveCompiledCachePath->resolveManifestPath();

        if ($fs->exists($compiledCachePath->toString())) {
            $fs->delete($compiledCachePath->toString());
        }

        $this->deleteOrphanedArtifacts();
    }

    private function deleteOrphanedArtifacts(): void
    {
        $fs = $this->filesystem ?? new Filesystem();
        $dir = $this->compiledCacheDirectory->toString();

        if (! $fs->exists($dir)) {
            return;
        }

        $files = $fs->listFilesByPattern($dir . '/*.php');

        if ($files === []) {
            return;
        }

        foreach ($files as $file) {
            if (basename($file) === 'manifest.php') {
                continue;
            }

            $content = $fs->read($file);

            if (str_contains($content, self::GENERATED_HEADER)) {
                $fs->delete($file);
            }
        }
    }
}
