<?php

declare(strict_types=1);

namespace Avax\Components\Application\Cache\System\Flows\Compiled\ClearCompiledCache;

use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheDirectory;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheManifest;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheName;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\DeleteCompiledCacheFile;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\ResolveCompiledCachePath;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\WriteCompiledCacheManifest;
use Avax\Components\Application\Cache\System\Foundation\Time\Clock;
use Avax\Components\Application\Filesystem\System\PublicSurface\Filesystem;

final class ClearCompiledCache
{
    private const string GENERATED_HEADER = 'This file is generated by Avax Compiled Cache';

    public function __construct(
        private readonly CompiledCacheDirectory $compiledCacheDirectory,
        private CompiledCacheManifest           $compiledCacheManifest,
        private Filesystem $filesystem,
        private Clock $clock,
    )
    {
    }

    public function clear(string $name): void
    {
        $compiledCacheName = new CompiledCacheName(name: $name);

        $deleteCompiledCacheFile = new DeleteCompiledCacheFile($this->compiledCacheDirectory, $this->filesystem);
        $deleteCompiledCacheFile->delete($compiledCacheName);

        $this->compiledCacheManifest->remove($compiledCacheName->toString());

        $resolveCompiledCachePath = new ResolveCompiledCachePath($this->compiledCacheDirectory);
        $compiledCachePath = $resolveCompiledCachePath->resolveManifestPath();

        $writeCompiledCacheManifest = new WriteCompiledCacheManifest($this->filesystem);
        $writeCompiledCacheManifest->write($this->compiledCacheManifest, $compiledCachePath);
    }

    public function clearAll(): void
    {
        foreach ($this->compiledCacheManifest->all() as $entry) {
            $deleter = new DeleteCompiledCacheFile($this->compiledCacheDirectory, $this->filesystem);
            $deleter->delete($entry->name);
        }

        $this->compiledCacheManifest = CompiledCacheManifest::empty($this->filesystem, $this->clock);

        $resolveCompiledCachePath = new ResolveCompiledCachePath($this->compiledCacheDirectory);
        $compiledCachePath = $resolveCompiledCachePath->resolveManifestPath();

        if ($this->filesystem->exists($compiledCachePath->toString())) {
            $this->filesystem->delete($compiledCachePath->toString());
        }

        $this->deleteOrphanedArtifacts();
    }

    private function deleteOrphanedArtifacts(): void
    {
        $dir = $this->compiledCacheDirectory->toString();

        if (! $this->filesystem->exists($dir)) {
            return;
        }

        $files = $this->filesystem->listFilesByPattern($dir . '/*.php');

        if ($files === []) {
            return;
        }

        foreach ($files as $file) {
            if (basename($file) === 'manifest.php') {
                continue;
            }

            $content = $this->filesystem->read($file);

            if (str_contains($content, self::GENERATED_HEADER)) {
                $this->filesystem->delete($file);
            }
        }
    }
}
