<?php

declare(strict_types=1);

namespace Avax\Components\Application\Cache\System\Flows\Compiled\ClearCompiledCache;

use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheDirectory;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheManifest;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\CompiledCacheName;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\DeleteCompiledCacheFile;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\ResolveCompiledCachePath;
use Avax\Components\Application\Cache\System\Capabilities\CompiledCache\ManageCompiledCache\WriteCompiledCacheManifest;

final class ClearCompiledCache
{
    private const string GENERATED_HEADER = 'This file is generated by Avax Compiled Cache';

    public function __construct(private readonly CompiledCacheDirectory $compiledCacheDirectory, private CompiledCacheManifest $compiledCacheManifest) {}

    public function clear(string $name) : void
    {
        $compiledCacheName = new CompiledCacheName(name: $name);

        $deleteCompiledCacheFile = new DeleteCompiledCacheFile(directory: $this->compiledCacheDirectory);
        $deleteCompiledCacheFile->delete(name: $compiledCacheName);

        $this->compiledCacheManifest->remove(name: $compiledCacheName->toString());

        $resolveCompiledCachePath = new ResolveCompiledCachePath(directory: $this->compiledCacheDirectory);
        $compiledCachePath = $resolveCompiledCachePath->resolveManifestPath();

        $writeCompiledCacheManifest = new WriteCompiledCacheManifest;
        $writeCompiledCacheManifest->write(manifest: $this->compiledCacheManifest, manifestPath: $compiledCachePath);
    }

    public function clearAll() : void
    {
        foreach ($this->compiledCacheManifest->all() as $entry) {
            $deleter = new DeleteCompiledCacheFile(directory: $this->compiledCacheDirectory);
            $deleter->delete(name: $entry->name);
        }

        $this->compiledCacheManifest = CompiledCacheManifest::empty();

        $resolveCompiledCachePath = new ResolveCompiledCachePath(directory: $this->compiledCacheDirectory);
        $compiledCachePath = $resolveCompiledCachePath->resolveManifestPath();

        if (file_exists($compiledCachePath->toString())) {
            unlink($compiledCachePath->toString());
        }

        $this->deleteOrphanedArtifacts();
    }

    private function deleteOrphanedArtifacts() : void
    {
        $dir = $this->compiledCacheDirectory->toString();

        if (! is_dir($dir)) {
            return;
        }

        $files = glob($dir . '/*.php');

        if ($files === false) {
            return;
        }

        foreach ($files as $file) {
            if (basename($file) === 'manifest.php') {
                continue;
            }

            $content = file_get_contents($file, offset: 0, length: 500);

            if ($content !== false && str_contains($content, self::GENERATED_HEADER)) {
                unlink($file);
            }
        }
    }
}
